basePath: /api
definitions:
  models.Alumni:
    properties:
      alamat:
        type: string
      angkatan:
        type: integer
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: string
      jurusan:
        type: string
      nama:
        type: string
      nim:
        type: string
      no_telepon:
        type: string
      tahun_lulus:
        type: integer
      updated_at:
        type: string
    type: object
  models.Pekerjaan:
    properties:
      alumni_id:
        type: string
      bidang_industri:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      deskripsi_pekerjaan:
        type: string
      gaji_range:
        type: string
      id:
        type: string
      lokasi_kerja:
        type: string
      nama_perusahaan:
        type: string
      posisi_jabatan:
        type: string
      status_pekerjaan:
        type: string
      tanggal_mulai_kerja:
        type: string
      tanggal_selesai_kerja:
        type: string
      updated_at:
        type: string
    type: object
host: 127.0.0.1:3000
info:
  contact: {}
  description: API untuk mengelola data dengan MongoDB menggunakan Clean Architecture
  title: Manajemen Alumni
  version: "1.0"
paths:
  /alumni:
    get:
      responses: {}
      summary: Dapatkan semua alumni
      tags:
      - Users - Alumni
    post:
      consumes:
      - application/json
      description: Menambahkan alumni ke database
      parameters:
      - description: Data Alumni
        in: body
        name: alumni
        required: true
        schema:
          $ref: '#/definitions/models.Alumni'
      produces:
      - application/json
      responses: {}
      summary: Membuat data alumni baru
      tags:
      - alumni
  /alumni/{id}:
    get:
      responses: {}
      summary: Dapatkan alumni berdasarkan id
      tags:
      - Users - Alumni
  /pekerjaan:
    get:
      responses: {}
      summary: Dapatkan semua pekerjaan
      tags:
      - Users - Pekerjaan
    post:
      consumes:
      - application/json
      description: Menambahkan pekerjaan ke database
      parameters:
      - description: Data Pekerjaan
        in: body
        name: pekerjaan
        required: true
        schema:
          $ref: '#/definitions/models.Pekerjaan'
      produces:
      - application/json
      responses: {}
      summary: Membuat data pekerjaan baru
      tags:
      - pekerjaan
  /pekerjaan/{id}:
    get:
      responses: {}
      summary: Dapatkan pekerjaan berdasarkan id
      tags:
      - Users - Pekerjaan
schemes:
- http
swagger: "2.0"
